plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}

group omfPackage + '.' + mdVersionShort

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly project(":omf-magicdraw-dependencies")
    compileOnly 'org.apache.commons:commons-lang3:3.12.0'
    api project(":omf-utils")
    api "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.23"
}

