plugins {
    id "io.github.gradle-nexus.publish-plugin" version "1.0.0"
}

// Config for the nexus publish plugin which automates the release of artifacts from the staging repository to the
// release repository. Doesn't work at the moment.
nexusPublishing {
    repositories {
        sonatype {
            username = mavenCentralUsername
            password = mavenCentralPwd
            nexusUrl.set(uri("https://s01.oss.sonatype.org/service/local/"))
            snapshotRepositoryUrl.set(uri("https://s01.oss.sonatype.org/content/repositories/snapshots/"))
        }
    }
}
