################################################################################
# @copyright Copyright (c) 2022-2023 Samares-Engineering
# @Licence: EPL 2.0
# @Author:   Quentin Cespédès, Clément Mezerette, Hugo Stinson
# @since     0.0.0
################################################################################

##
# Do not leave sensitive info here (i.e. passwords, usernames, ip adresses, etc.)
##

#Project
version=2.1.13-SNAPSHOT
omfPackage=com.samares-engineering.omf
coreFrameworkArtefactId=omf-core-framework
testFrameworkArtefactId=omf-test-framework
publicFeaturesArtefactId=omf-public-features
utilsArtefactId=omf-utils
examplePluginArtefactId=omf-example-plugin

#Local delivery
localDeliverPath = C:/git/OMF_Delivery

#Used in Nexus & zip name to differentiate between plugin for different versions of Magicdraw
mdVersionShort=2022x_Refresh2
#mdVersionShort=2021x_R2

#Example Plugin
pluginName=OpenMBSEFrameworkExamplePlugin
pluginId=012345
pluginMainClass=com.samares_engineering.omf.omf_example_plugin.OMFExamplePlugin

#Test
testPluginName=OMF TEST Plugin
testPluginId=012346
testPluginPackage=com.samares_engineering.omf.omf_example_plugin.test
testPluginMainClass=com.samares_engineering.omf.omf_example_plugin.test.OMFExampleTestPlugin
testRetriever=com.samares_engineering.omf.omf_example_plugin.test.ProjectRetriever

#Debug
javaDebugPort = 5005

