################################################################################
# @copyright Copyright (c) 2022-2023 Samares-Engineering
# @Licence: EPL 2.0
# @Author:   Quentin Cespédès, Clément Mezerette, Hugo Stinson
# @since     0.0.0
################################################################################

##
# Do not leave sensitive info here (i.e. passwords, usernames, ip adresses, etc.)
##

#Project
version=0.0.87-SNAPSHOT
omfPackage=com.samares-engineering.omf
coreFrameworkArtefactId=omf-core-framework
testFrameworkArtefactId=omf-test-framework
publicFeaturesArtefactId=omf-public-features
utilsArtefactId=omf-utils
examplePluginArtefactId=omf-example-plugin

#Local delivery
localDeliverPath = C:/git/OMF_Delivery
mavenRepoGroupId = com.samares-engineering.omf

#Used in Nexus & zip name to differentiate between plugin for different versions of Magicdraw
mdVersionShort=2021x_R2
mdMavenArchive=com.nomagic:mcse:2021x_Refresh2_HF2@zip

#Example Plugin
pluginName=OpenMBSEFrameworkExamplePlugin
pluginId=012345
pluginMainClass=com.samares_engineering.omf.omf_example_plugin.OpenMBSEFrameworkPlugin
descriptorFileName=MDR Plugin OpenMBSEFramework 012345 descriptor.xml
generatedDistFolderName=generated-dist

#Test
testPluginName=OMF TEST Plugin
testPluginId=012346
testPluginPackage=com.samares_engineering.omf.omf_example_plugin.test
testPluginMainClass=com.samares_engineering.omf.omf_example_plugin.test.TestPlugin
testDescriptorFileName=MDR Test Plugin OpenMBSEFramework 012345 descriptor.xml
testDistFolderName=generated-test-dist
testLauncher=com.samares_engineering.omf.omf_test_framework.BatchLauncher
testRetriever=com.samares_engineering.omf.omf_example_plugin.test.ProjectRetriever

