################################################################################
# @copyright Copyright (c) 2022-2023 Samares-Engineering
# @Licence: EPL 2.0
# @Author:   Quentin Cespédès, Clément Mezerette, Hugo Stinson
# @since     0.0.0
################################################################################

##
# Do not leave sensitive info here (i.e. passwords, usernames, ip adresses, etc.)
##

#Project
version=0.0.82-SNAPSHOT

#Local delivery
localDeliverPath = C:/git/OMF_Delivery

#Used in Nexus & zip name to differentiate between plugin for different versions of Magicdraw
mdVersionShort=2021x

#Plugin
pluginName=OpenMBSEFrameworkPlugin
pluginId=012345
pluginPackage=com.samares.omf.plugin
pluginMainClass=com.samares.omf.plugin.OpenMBSEFrameworkPlugin
descriptorFileName=MDR Plugin OpenMBSEFramework 012345 descriptor.xml
generatedDistFolderName=generated-dist

#Test
testPluginName=OMF TEST Plugin
testPluginId=012346
testPluginPackage=com.samares.omf.plugin.test
testPluginMainClass=com.samares.omf.plugin.test.TestPlugin
testDescriptorFileName=MDR Test Plugin OpenMBSEFramework 012345 descriptor.xml
testDistFolderName=generated-test-dist
testLauncher=com.samares.omf.test.BatchLauncher
testRetriever=com.samares.omf.plugin.test.utils.ProjectRetriever

