pluginManagement {
    repositories {
        maven {
            allowInsecureProtocol = true
            credentials {
                username nexusUsername
                password nexusPassword
            }
            url = "$nexusUrl/maven-releases"
            name 'Samares Nexus releases'
        }
        maven {
            allowInsecureProtocol = true
            credentials {
                username nexusUsername
                password nexusPassword
            }
            url = "$nexusUrl/maven-snapshots"
            name 'Samares Nexus snapshots'
        }
        gradlePluginPortal()
    }

    // Use the gradle plugin from the local repository to allow testing changes without having to publish the plugin
    includeBuild 'omf-gradle-plugin'
}

rootProject.name = 'OpenMBSEFramework'
include 'omf-test-framework'
include 'omf-core-framework'
include 'omf-utils'
include 'omf-magicdraw-dependencies'
include 'omf-public-features'
include 'omf-example-plugin'
