pluginManagement {
    repositories {
        maven {
            allowInsecureProtocol = true
            credentials {
                username mavenRepoUsername
                password mavenRepoPassword
            }
            url = mavenRepoUrl
            name 'MavenReleaseRepo'
        }
        maven {
            allowInsecureProtocol = true
            credentials {
                username mavenRepoUsername
                password mavenRepoPassword
            }
            url = mavenSnapshotRepoUrl
            name 'MavenSnapshotRepo'
        }
        gradlePluginPortal()
    }

    // Use the gradle plugin from the local repository to allow testing changes without having to publish the plugin
    includeBuild 'omf-gradle-plugin'
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '1.9.23'
    }
}

rootProject.name = 'open-mbse-framework'
include 'omf-test-framework'
include 'omf-core-framework'
include 'omf-utils'
include 'omf-magicdraw-dependencies'
include 'omf-public-features'
include 'omf-example-plugin'
include 'smart-private'

