plugins {
    id 'java-library'
}

group omfPackage + '.' + mdVersionShort

repositories {
    maven {
        allowInsecureProtocol = true
        credentials {
            username mavenRepoUsername
            password mavenRepoPassword
        }
        url = mavenRepoUrl
        name 'SamaresPrivateMavenRepo'
    }
}

configurations {
    mdApplicationArchive
}

dependencies {
    def archiveMap = [
            "2021x_R1"                 : "com.nomagic.magicdraw:MagicDraw:2021x_RF1@zip",
            "2021x_R2"                 : "com.nomagic:mcse:2021x_Refresh2_HF2@zip",
            "2022x_Refresh2"           : "com.nomagic:mcse:2022x_Refresh2@zip",
            "2024x"                    : "com.nomagic:mcse:2024x@zip",
            "2024x_Refresh2"           : "com.nomagic:mcse:2024x_Refresh2@zip",
            "2024x_Refresh2_HF2"       : "com.nomagic:mcse:2024x_Refresh2_HF2@zip",
            "2024x_Refresh2_SysmlV2"   : "com.nomagic:mcse:2024x_Refresh2_SysmlV2@zip",
            "MSoSA_2026x"              : "com.nomagic.magicdraw:msosa:2026x@zip",
            "2026x"                    : "com.nomagic:mcse:2026x@zip",
    ]
    if (mdVersionShort == "local" && localMagicdrawArchive) {
        mdApplicationArchive files(localMagicdrawArchive)
    } else if (archiveMap.containsKey(mdVersionShort)) {
        mdApplicationArchive archiveMap[mdVersionShort]
    } else {
        throw new GradleException("MagicDraw version not supported: $mdVersionShort")
    }

    // This ensures classpath load order to match the MagicDraw provided order and then includes extras needed for non-OpenAPI stuff.
    api fileTree(dir: "$project.parent.buildDir/install", include: ['lib/**.jar'])

    // SysML and MDCustomizationForSysMLProfile
    api fileTree(dir: "$project.parent.buildDir/install/plugins/com.nomagic.requirements", include: ['lib/**.jar'])
}

project.tasks.register('installMagicDraw') {
    it.group = "_install"
    def cameoConf = project.configurations.mdApplicationArchive
    def isAlreadyInstalled = new File("$project.parent.buildDir/install").exists()
    it.doLast {
        if (cameoConf.isEmpty()) {
            throw new GradleException("Can't install Magicdraw as magicdraw dependency has not been configured")
        } else if (isAlreadyInstalled) {
            print "Skipping installing Magicdraw as it is already installed"
        } else {
            print "Installing Magicdraw"
            project.copy {
                from project.zipTree(cameoConf.first())
                into "$project.parent.buildDir/install"
            }
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(jvmVersion)
    }
}

compileJava.dependsOn installMagicDraw