import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

plugins {
    id 'maven-publish'
    id 'com.kncept.junit.reporter' version '2.1.0'
    id 'com.samares-engineering.omf.omf-gradle-plugin'
    id 'signing'
}

group omfPackage + '.' + mdVersionShort

// ============================= GLOBAL VARIABLES DECLARATION =============================

ext.thePluginDeliveryName = omfPackage + ".plugin" + "_" + version
ext.theTestPluginDeliveryName = testPluginPackage + "_" + version
ext.srcLocalDestinationDir = localDeliverPath + "/" + omfPackage + "/" + mdVersionShort + "/" + omfPackage + "_" +
        mdVersionShort + "_" + version
ext.buildNumber = project.hasProperty('buildNumber') ? project.getProperty('buildNumber') : System.currentTimeSeconds()
ext.timestamp = DateTimeFormatter.ofPattern("yyyy-MM-dd-HH:mm").format(LocalDateTime.now())
ext.isRelease = !version.endsWith("-SNAPSHOT")
var userDirName = System.getProperty("user.dir")
var projectsResources = "\\..\\..\\src\\test\\resources\\projects"
var resourcesDir = userDirName + projectsResources

// ============================= REPOSITORY DECLARATION & DEPENDENCIES =============================

repositories {
    maven {
        allowInsecureProtocol = true
        credentials {
            username mavenRepoUsername
            password mavenRepoPassword
        }
        url = mavenRepoUrl
        name 'MavenReleaseRepo'
    }
    maven {
        allowInsecureProtocol = true
        credentials {
            username mavenRepoUsername
            password mavenRepoPassword
        }
        url = mavenSnapshotRepoUrl
        name 'MavenSnapshotRepo'
    }
    mavenCentral()
}

/*
 Use the following dependency configurations :
    - mdApplicationArchive: declares the MagicDraw zip archive, should only be used once
    - mdLibrary: declares dependencies that are added to the classpath when we launch MagicDraw. Only the libraries
    in the magicdraw /lib folder should be added here.
    - pluginLibrary: for dependencies that are required by the plugin at runtime
    - testPluginLibrary: for dependencies that are required by the test plugin at runtime
    - zippedMDPlugin: declares a plugin zip archive to be automatically installed in MagicDraw when we launch it.
    - otherMDPluginLibrary: declares dependencies of a plugin that is marked as <required-plugin> in the plugin.xml.
    In such cases MagicDraw will add the plugin to the classpath at runtime automatically but we need to add the jars
    of the plugin in Gradle to be able to compile the code.
 */
dependencies {
    mdApplicationArchive mdMavenArchive

    mdLibrary fileTree(dir: 'build/install/lib', include: ['*.jar', '**/*.jar'])

    pluginLibrary project(':omf-test-framework')
    pluginLibrary project(':omf-core-framework')
    pluginLibrary project(':omf-public-features')

    testPluginLibrary 'ant:ant-junit:1.6.5'
    testPluginLibrary 'org.apache.ant:ant:1.8.2'
    testPluginLibrary 'org.eclipse.jetty:jetty-client:9.4.38.v20210224'
    testPluginLibrary project(':omf-test-framework')
    testPluginLibrary project(':omf-core-framework')

    zippedMDPlugin "com.nomagic.magicdraw:devtools:2021x_Refresh2@zip"
    otherMDPluginLibrary fileTree(dir: 'build/install/plugins/com.nomagic.requirements', include: ['lib/**.jar'])
}

// Samares gradle plugin configuration
mdPluginBuild {
    humanVersion = version
    buildTimestamp = timestamp
    myPluginName = pluginName
    myPackage = "${omfPackage}.plugin"
    myPluginId = pluginId
    myPluginMainClass = pluginMainClass
    localDeliveryDirectory = srcLocalDestinationDir
    distributionFolderName = generatedDistFolderName
    pluginDeliveryName = thePluginDeliveryName
    humanVersionCore = "0.0.0"
    testPluginDeliveryName = theTestPluginDeliveryName
    myTestPluginId = testPluginId
    myTestPluginName = testPluginName
    myTestPluginMainClass = testPluginMainClass
    myTestPackage = testPluginPackage
    testDistributionFolderName = testDistFolderName
}

// ======================== JAVA TASKS CONFIG ========================
// Configuration for javaExec Tasks
tasks.withType(JavaExec) {
    classpath = configurations.mdLibrary
    workingDir 'build/install'
    args 'TESTER'
}

// ======================== GRADLE TASKS DEFINITION ========================
// Customize clean task to not remove all the files from build dir
clean {
    group '_dev'
    // Don't delete build dir and sub Dir
    delete = []
    // Delete those specific dir :
    delete 'build/classes', 'build/distributions', 'build/generated',
            "build/$generatedDistFolderName", 'build/libs', 'build/plugin',
            'build/reports', "build/$testDistFolderName",
            'build/tmp'
}

// Task to delete plugins created before a new build.
// Previously in custom task clean, it was blocking the "hot debug" mode
task deletePlugins(type: Delete) {
    group '_dev'
    delete 'build/install/plugins/' + omfPackage,
            'build/tmp', 'build/install/plugins/' + omfPackage,
            'build/install/plugins/' + testPluginPackage,
            'build/test-reports'
}

task fatJar(type: Jar) {
    baseName = 'omf-fatjar'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.allSource
    from { configurations.pluginLibrary.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}

// Encoding option for all javaCompile tasks
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

// Source definition for jar building
task sourceJar(type: Jar) {
    archiveClassifier.set("sources")
    from sourceSets.main.allSource
}
sourceJar.dependsOn classes


// ============TESTS SETUP (TASKS, DISTRIBUTION, JVM)========================
task testJar(type: Jar) {
    archiveClassifier.set("tests")
    from sourceSets.test.output.classesDirs
}


// Args for jvm (used with commandLineActionLauncher from CAMEO)
def testArgs = [
        '-Desi.system.config=data/application.conf',
        '-Dcom.nomagic.magicdraw.commandline.action=' + testLauncher,
        '-Dtests.resources=' + resourcesDir
]

def twcArgs = [
        "-DserverIp=$ipServer",
        "-DuserName=$twcUsername",
        "-DuserPwd=$twcPassword",
        "-Dtest=true"
]

// To launch units tests in CAMEO from IntelliJ
task runTest(type: JavaExec) {
    group '_dev'
    mainClass = 'com.nomagic.magicdraw.commandline.CommandLineActionLauncher'
    jvmArgs += testArgs
    jvmArgs += twcArgs
    args += '-verbose'
}
runTest.dependsOn installTestPlugin

task runTestNoLog(type: JavaExec) {
    group '_dev'
    mainClass = 'com.nomagic.magicdraw.commandline.CommandLineActionLauncher'
    jvmArgs += testArgs
    jvmArgs += twcArgs
}
runTestNoLog.dependsOn installTestPlugin

def modelSaveArgs = [
        "-Dcom.nomagic.magicdraw.commandline.action=" + testRetriever,
        "-Dtest=false",
        "-DprojectInitName=ModelForTestAuto_Init.mdzip",   // Mandatory
        "-DprojectFinalName=ModelForTestAuto_Final.mdzip", // Optional, can be left blanked
        "-DsaveLocation=" + resourcesDir
]

task retrieveModel(type: JavaExec) {
    group '_dev'
    main = 'com.nomagic.magicdraw.commandline.CommandLineActionLauncher'
    jvmArgs += testArgs
    jvmArgs += twcArgs
    jvmArgs += modelSaveArgs
    args += '-verbose'
}
retrieveModel.dependsOn installTestPlugin

tasks.all { task ->
    if (task.name.startsWith('publish')) {
        task.dependsOn zipPluginLocally
        task.dependsOn javadoc
        task.dependsOn sourceJar
        task.dependsOn ":omf-test-framework:jar"
        task.dependsOn ":omf-core-framework:jar"
        task.dependsOn ":omf-utils:jar"
        task.dependsOn ":omf-public-features:jar"
    }
}

tasks.junitHtmlReport.doLast {
    exec {
        workingDir "$buildDir/test-reports/TEST-HTML"
        //on windows:
        commandLine 'cmd', '/c', 'start index.html'
    }
}

// ============================= TASK CONFIGURATION =============================
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
    withSourcesJar()
    withJavadocJar()
}

signing {
    if (isRelease) {
        useGpgCmd()
        sign(publishing.publications)
    }
}

ext.setDefaultPomValues = { pom ->
    // Project url
    pom.url = "https://gitlab.com/samaresengineeringpublic/samaresmbseframework"
    pom.inceptionYear = '2022'

    pom.licenses {
        owner.license {
            name = 'Eclipse Public License - v 2.0'
            url = 'https://www.eclipse.org/legal/epl-2.0/'
        }
    }

    pom.developers {
        owner.developer {
            id = 'hugostinson'
            name = 'Hugo Stinson'
            email = 'hugo.stinson@samares-engineering.com'
        }

        owner.developer {
            id = 'clementmezerette'
            name = 'Clement Mezerette'
            email = 'clement.mezerette@samares-engineering.com'
        }

        owner.developer {
            id = 'quentincespedes'
            name = 'Quentin Cespedes'
            email = 'quentin.cespedes@samares-engineering.com'
        }
    }

    pom.scm {
        connection = "scm:git:git:https://gitlab.com/samaresengineeringpublic/samaresmbseframework.git"
        developerConnection = "scm:git:git:https://gitlab.com/samaresengineeringpublic/samaresmbseframework.git"
        url = "https://gitlab.com/samaresengineeringpublic/samaresmbseframework"
    }
}

publishing {
    repositories {
        maven {
            name = "PrivateSamaresRepo"
            credentials {
                username mavenRepoUsername
                password mavenRepoPassword
            }
            def releasesRepoUrl = mavenRepoUrl
            def snapshotsRepoUrl = mavenSnapshotRepoUrl
            url = isRelease ? releasesRepoUrl : snapshotsRepoUrl
            allowInsecureProtocol true
        }

        maven {
            name = "MavenCentral"
            def releasesRepoUrl = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
            def snapshotsRepoUrl = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
            url = isRelease ? releasesRepoUrl : snapshotsRepoUrl
            credentials {
                username = mavenCentralUsername
                password = mavenCentralPwd
            }
        }
    }

    publications {
        // Publish built plugin .zip to Nexus repo
        examplePluginZip(MavenPublication) {
            groupId = omfPackage + "." + mdVersionShort
            artifactId = examplePluginArtefactId
            artifact("$buildDir/builtPlugin/$project.version/${thePluginDeliveryName}.zip")
            setDefaultPomValues(pom)
            pom {
                name = "$examplePluginArtefactId:$mavenRepoGroupId"
                description = "An example plugin demonstrating use of the framework."
            }
        }

        coreFrameworkJar(MavenPublication) {
            groupId = omfPackage + "." + mdVersionShort
            artifactId = coreFrameworkArtefactId
            from project(":omf-core-framework").components.java
            setDefaultPomValues(pom)
            pom {
                name = "$coreFrameworkArtefactId:$mavenRepoGroupId"
                description = "A framework for developing MagicDraw plugins."
            }
        }

        testFrameworkJar(MavenPublication) {
            groupId = omfPackage + "." + mdVersionShort
            artifactId = testFrameworkArtefactId
            from project(":omf-test-framework").components.java
            setDefaultPomValues(pom)
            pom {
                name = "$testFrameworkArtefactId:$mavenRepoGroupId"
                description = "A framework for developing functional tests for MagicDraw plugins."
            }
        }

        publicFeaturesJar(MavenPublication) {
            groupId = omfPackage + "." + mdVersionShort
            artifactId = publicFeaturesArtefactId
            from project(":omf-public-features").components.java
            setDefaultPomValues(pom)
            pom {
                name = "$publicFeaturesArtefactId:$mavenRepoGroupId"
                description = "A collection of open source features that can be integrated to third-party plugins."
            }
        }

        utilsJar(MavenPublication) {
            groupId = omfPackage + "." + mdVersionShort
            artifactId = utilsArtefactId
            from project(":omf-utils").components.java
            setDefaultPomValues(pom)
            pom {
                name = "$utilsArtefactId:$mavenRepoGroupId"
                description = "A collection of utilities methods used in the framework as well as helpers for the " +
                        "MagicDraw public api that can be useful for plugin regardless of whether they use the " +
                        "framework or not."
            }
        }

        // Publish plugin .jar to Nexus repo
        //jar(MavenPublication) {
        //    groupId = omfPackage + "." + mdVersionShort
        //    artifactId = "omf-fatJar"
        //    artifact fatJar
        //}
    }
}

junitHtmlReport {
    testResultsDir = "test-reports/TEST-XML"
    testReportsDir = "test-reports/TEST-HTML"
}

installPlugin.dependsOn deletePlugins
compileJava.dependsOn clean
runTestNoLog.finalizedBy 'junitHtmlReport'
runTest.finalizedBy 'junitHtmlReport'
