apply plugin: 'groovy'
apply plugin: 'java-gradle-plugin'
apply plugin: 'maven-publish'

group 'com.samares-engineering.omf.omf-gradle-plugin'
version '0.115.16-SNAPSHOT'
ext.mainClass = 'com.samares_engineering.omf.omf_gradle_plugin.OmfGradlePlugin'
ext.isRelease = !version.endsWith("-SNAPSHOT")

dependencies {
    testImplementation 'org.spockframework:spock-core:2.1-groovy-3.0'
}

gradlePlugin {
    plugins {
        omfGradlePlugin {
            id = group
            implementationClass = mainClass
        }
    }
}

publishing {
    repositories {
        maven {
            allowInsecureProtocol true
            credentials {
                username mavenRepoUsername
                password mavenRepoPassword
            }
            def releasesRepoUrl = mavenRepoUrl
            def snapshotsRepoUrl = mavenSnapshotRepoUrl
            url = isRelease ? releasesRepoUrl : snapshotsRepoUrl
        }
    }
}

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }

}

jar {
    manifest {
        attributes 'Implementation-Title': project.group,
                'Implementation-Version': project.version,
                'Main-Class': mainClass
    }
}